name: Update Major Version Tag
on:
  push:
    tags:
      - "v*"
jobs:
  update-major:
    name: Update Major Version Tag
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@81156e925c68190d58d061ebdde01f0d869f22db
